steps:
- name: 'busybox'
  args: ['sleep', '10']
options:
  workerPool: 'projects/git-proxy-bug-bash5/locations/australia-southeast1/workerPools/bug-bash-pool'
gitConfig:
  http:
    proxySecretVersionName: 'projects/740864308113/secrets/bug-bash-secret/versions/latest'
source:
  gitSource:
    url: 'https://github.com/elweb9858/golang-sample'
    revision: 'main'
