steps:
- name: 'busybox'
  args: ['sleep', '10']
options:
  workerPool: 'projects/git-proxy-bug-bash6/locations/australia-southeast1/workerPools/private-pool-a'
gitConfig:
  http:
    proxySecretVersionName: 'projects/931495833756/secrets/ricwong-secret/versions/latest'
source:
  gitSource:
    url: 'https://github.com/richardwong8/golang-sample'
    revision: 'main'
